"""Turn benchmark JSON results into a single markdown report.

Usage:
  python -m bench.report              # uses bench/results/*.json
  python -m bench.report --out report.md
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent


def load_all(results_dir: Path) -> list[dict]:
    summaries = []
    for f in sorted(results_dir.glob("*.json")):
        try:
            summaries.append(json.loads(f.read_text()))
        except Exception:
            continue
    return summaries


def render(summaries: list[dict]) -> str:
    if not summaries:
        return "# Benchmark report\n\nNo results found.\n"

    # Keep most recent run per label
    latest: dict[str, dict] = {}
    for s in summaries:
        key = s.get("label", "unknown")
        if key not in latest or s["timestamp"] > latest[key]["timestamp"]:
            latest[key] = s

    order = ["full", "no-memory", "no-planner", "no-tools", "no-reflection"]
    rows = [latest[k] for k in order if k in latest]
    for k, v in latest.items():
        if v not in rows:
            rows.append(v)

    lines: list[str] = []
    lines.append("# Benchmark report\n")
    lines.append(f"Ablations ({len(rows)}), most recent per label.\n")

    # Summary table
    lines.append("## Summary\n")
    lines.append("| Label | Tasks | Overall score | Success rate | Tool-call hit | Mean latency | Runtime |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for s in rows:
        tcr = s.get("tool_call_success_rate")
        lines.append(
            f"| `{s['label']}` "
            f"| {s['task_count']} "
            f"| {s['overall_score']:.3f} "
            f"| {s['success_rate']:.1%} "
            f"| {'n/a' if tcr is None else f'{tcr:.1%}'} "
            f"| {s['mean_latency_ms']} ms "
            f"| {s['total_runtime_s']}s |"
        )

    # Ablation deltas vs full
    full = latest.get("full")
    if full:
        lines.append("\n## Ablation deltas (vs. `full`)\n")
        lines.append("| Label | Δ overall score | Δ success rate |")
        lines.append("|---|---:|---:|")
        for s in rows:
            if s["label"] == "full":
                continue
            dscore = s["overall_score"] - full["overall_score"]
            drate = s["success_rate"] - full["success_rate"]
            lines.append(f"| `{s['label']}` | {dscore:+.3f} | {drate:+.1%} |")

    # Per-category breakdown for full
    if full:
        lines.append("\n## Per-category scores (`full` run)\n")
        lines.append("| Category | n | Avg score |")
        lines.append("|---|---:|---:|")
        for cat, info in full.get("by_category", {}).items():
            lines.append(f"| {cat} | {info['n']} | {info['avg_score']:.3f} |")

    # Flag grid
    lines.append("\n## Flags per run\n")
    lines.append("| Label | memory | planner | tools | reflection |")
    lines.append("|---|:-:|:-:|:-:|:-:|")
    for s in rows:
        f = s.get("flags", {})
        lines.append(
            f"| `{s['label']}` "
            f"| {'✅' if f.get('memory') else '❌'} "
            f"| {'✅' if f.get('planner') else '❌'} "
            f"| {'✅' if f.get('tools') else '❌'} "
            f"| {'✅' if f.get('reflection') else '❌'} |"
        )

    lines.append("\n---")
    lines.append("\n_Generated by `python -m bench.report`._")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(ROOT / "bench" / "results"))
    ap.add_argument("--out", default=str(ROOT / "bench" / "results" / "REPORT.md"))
    args = ap.parse_args()

    results_dir = Path(args.results)
    summaries = load_all(results_dir)
    md = render(summaries)
    Path(args.out).write_text(md)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
