"""Benchmark runner with ablations.

Usage:
  python -m bench.runner --profile minimal
  python -m bench.runner --ablation no-memory
  python -m bench.runner --ablation no-tools
  python -m bench.runner --ablation no-planner
  python -m bench.runner --ablation no-reflection

Produces a JSON file in bench/results/<label>_<timestamp>.json and a short
human summary to stdout. The markdown report is generated by bench.report.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
import time
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agentos.config import Settings  # noqa: E402
from agentos.eval.scorer import score_expected  # noqa: E402
from agentos.llm import build_llm  # noqa: E402
from agentos.memory.store import MemoryStore  # noqa: E402
from agentos.runtime import TraceStore, run_agent  # noqa: E402
from agentos.tools.registry import build_default_registry  # noqa: E402


ABLATIONS = {
    "full":          {},
    "no-memory":     {"enable_memory": False},
    "no-planner":    {"enable_planner": False},
    "no-tools":      {"enable_tools": False},
    "no-reflection": {"enable_reflection": False},
}


async def run_benchmark(label: str, profile: str, tasks_file: Path,
                        db_path: str, max_tasks: int | None = None) -> dict:
    overrides = ABLATIONS[label]
    settings = Settings(profile=profile, db_path=db_path, **overrides)
    settings.apply_profile()

    llm = build_llm(settings)
    memory = MemoryStore(settings.db_path)
    tools = build_default_registry(settings)
    traces = TraceStore(settings.db_path)

    tasks_data = json.loads(tasks_file.read_text())
    tasks = tasks_data["tasks"]
    if max_tasks:
        tasks = tasks[:max_tasks]

    results = []
    start_all = time.perf_counter()
    for i, t in enumerate(tasks, 1):
        tstart = time.perf_counter()
        try:
            r = await run_agent(
                t["prompt"],
                llm=llm, tools=tools, memory=memory, traces=traces,
                config=settings,
                expected=t,
            )
            elapsed = time.perf_counter() - tstart

            # Score via expected_contains
            sc = score_expected(r.answer, t)
            sc = sc if sc is not None else r.score

            # expected_tool hit?
            tool_ok = None
            if t.get("expected_tool"):
                called = [tc.get("tool") for tc in r.tool_calls]
                tool_ok = t["expected_tool"] in called

            results.append({
                "task_id": t["id"],
                "category": t["category"],
                "difficulty": t.get("difficulty"),
                "prompt": t["prompt"],
                "answer": r.answer,
                "score": sc,
                "heuristic_score": r.score,
                "tool_calls": [tc.get("tool") for tc in r.tool_calls],
                "expected_tool": t.get("expected_tool"),
                "tool_match": tool_ok,
                "expected_behavior": t.get("expected_behavior"),
                "status": r.status,
                "steps": r.steps,
                "latency_ms": int(elapsed * 1000),
                "run_id": r.run_id,
                "error": r.error,
            })
            print(f"  [{i}/{len(tasks)}] {t['id']:<10} score={sc:.2f} "
                  f"{r.status:<8} {int(elapsed*1000)}ms")
        except Exception as e:
            results.append({
                "task_id": t["id"], "error": str(e), "score": 0.0,
                "status": "crash"
            })
            print(f"  [{i}/{len(tasks)}] {t['id']:<10} CRASH: {e}")

    total_elapsed = time.perf_counter() - start_all

    # --- aggregate ---
    by_cat: dict[str, list] = {}
    for r in results:
        by_cat.setdefault(r.get("category", "unknown"), []).append(r)

    summary = {
        "label": label,
        "profile": profile,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "task_count": len(results),
        "overall_score": _avg([r.get("score", 0.0) for r in results]),
        "success_rate": sum(1 for r in results if (r.get("score") or 0) >= 0.6) / max(len(results), 1),
        "tool_call_success_rate": _tool_success_rate(results),
        "mean_latency_ms": int(_avg([r.get("latency_ms", 0) for r in results])),
        "total_runtime_s": round(total_elapsed, 2),
        "flags": settings.describe()["flags"],
        "by_category": {
            cat: {
                "n": len(rs),
                "avg_score": round(_avg([r.get("score", 0) for r in rs]), 3),
            }
            for cat, rs in by_cat.items()
        },
        "results": results,
    }
    return summary


def _avg(xs: list) -> float:
    xs = [x for x in xs if isinstance(x, (int, float))]
    return sum(xs) / len(xs) if xs else 0.0


def _tool_success_rate(results: list[dict]) -> float | None:
    checked = [r for r in results if r.get("expected_tool")]
    if not checked:
        return None
    return sum(1 for r in checked if r.get("tool_match")) / len(checked)


def save(summary: dict, out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = out_dir / f"{summary['label']}_{ts}.json"
    out.write_text(json.dumps(summary, indent=2, default=str))
    return out


def print_summary(summary: dict) -> None:
    print()
    print(f"=== {summary['label']} | profile={summary['profile']} ===")
    print(f"  tasks:           {summary['task_count']}")
    print(f"  overall score:   {summary['overall_score']:.3f}")
    print(f"  success rate:    {summary['success_rate']:.2%}")
    if summary["tool_call_success_rate"] is not None:
        print(f"  tool-call hit:   {summary['tool_call_success_rate']:.2%}")
    print(f"  mean latency:    {summary['mean_latency_ms']} ms")
    print(f"  runtime:         {summary['total_runtime_s']}s")
    print(f"  flags:           {summary['flags']}")
    print("  by category:")
    for cat, s in summary["by_category"].items():
        print(f"    - {cat:<18} n={s['n']:<3} avg={s['avg_score']}")


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="minimal", choices=["minimal", "full"])
    ap.add_argument("--ablation", default="full",
                    choices=list(ABLATIONS.keys()))
    ap.add_argument("--tasks", default=str(ROOT / "bench" / "tasks.json"))
    ap.add_argument("--db", default=str(ROOT / "data" / "bench.db"))
    ap.add_argument("--max-tasks", type=int, default=None)
    ap.add_argument("--all-ablations", action="store_true",
                    help="Run every ablation back-to-back.")
    args = ap.parse_args()

    out_dir = ROOT / "bench" / "results"
    tasks_file = Path(args.tasks)

    labels = list(ABLATIONS.keys()) if args.all_ablations else [args.ablation]
    for label in labels:
        # fresh DB per ablation to keep runs independent
        db = str(Path(args.db).with_name(f"bench_{label}.db"))
        Path(db).unlink(missing_ok=True)
        summary = await run_benchmark(label, args.profile, tasks_file, db,
                                      args.max_tasks)
        out = save(summary, out_dir)
        print_summary(summary)
        print(f"  saved:           {out.relative_to(ROOT)}")


if __name__ == "__main__":
    asyncio.run(main())
